"""empty message

Revision ID: 07c0b76f8cbd
Revises: c5aaf7bd32ee
Create Date: 2019-02-10 22:12:47.560059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07c0b76f8cbd'
down_revision = 'c5aaf7bd32ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('Plan', sa.Column('date', sa.Date(), nullable=True))
    # op.add_column('Plan', sa.Column('training_phase', sa.String(length=128), nullable=True))
    # op.add_column('Plan', sa.Column('tss_compl', sa.Integer(), nullable=True))
    # op.add_column('Plan', sa.Column('tss_plan', sa.Integer(), nullable=True))
    # op.add_column('Plan', sa.Column('week', sa.Integer(), nullable=True))
    # op.drop_column('Plan', 'TrainingPhase')
    # op.drop_column('Plan', 'Date')
    # op.drop_column('Plan', 'Week')
    # op.drop_column('Plan', 'TSScompl')
    # op.drop_column('Plan', 'TSSplan')
    op.alter_column('Plan', 'TrainingPhase', new_column_name='training_phase', existing_type=sa.String(length=128), existing_server_default=False, existing_nullable=None)
    op.alter_column('Plan', 'TSSplan', new_column_name='tss_plan', existing_type=sa.Integer(), existing_server_default=False, existing_nullable=None)
    op.alter_column('Plan', 'TSScompl', new_column_name='tss_compl', existing_type=sa.Integer(), existing_server_default=False, existing_nullable=None)
    op.alter_column('Plan', 'Week', new_column_name='week', existing_type=sa.Integer(), existing_server_default=False, existing_nullable=None)
    op.alter_column('Plan', 'Date', new_column_name='date', existing_type=sa.Date(), existing_server_default=False, existing_nullable=None)
    # ### end Alembic commands ###


# def downgrade():
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('Plan', sa.Column('TSSplan', mysql.DECIMAL(precision=10, scale=0), nullable=True))
    # op.add_column('Plan', sa.Column('TSScompl', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # op.add_column('Plan', sa.Column('Week', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    # op.add_column('Plan', sa.Column('Date', sa.DATE(), nullable=True))
    # op.add_column('Plan', sa.Column('TrainingPhase', mysql.VARCHAR(length=128), nullable=True))
    # op.drop_column('Plan', 'week')
    # op.drop_column('Plan', 'tss_plan')
    # op.drop_column('Plan', 'tss_compl')
    # op.drop_column('Plan', 'training_phase')
    # op.drop_column('Plan', 'date')
    # op.create_table('testPlan',
    # sa.Column('id', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False),
    # sa.Column('date', sa.DATE(), nullable=True),
    # sa.Column('week', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    # sa.Column('tss_plan', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    # sa.Column('tss_compl', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    # sa.Column('training_phase', mysql.VARCHAR(length=128), nullable=True),
    # mysql_default_charset='latin1',
    # mysql_engine='InnoDB'
    # )
    # ### end Alembic commands ###
