"""empty message

Revision ID: 28308995a746
Revises: 
Create Date: 2019-02-01 22:35:37.275439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28308995a746'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Plan', sa.Column('TrainingPhase', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_UserDetails_Name'), 'UserDetails', ['Name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_UserDetails_Name'), table_name='UserDetails')
    op.drop_column('Plan', 'TrainingPhase')
    # ### end Alembic commands ###
