"""empty message

Revision ID: bf5d8164fec5
Revises: 
Create Date: 2019-01-06 22:42:40.761638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf5d8164fec5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Move_2018_04_03_17_13_06')
    op.drop_table('Move_2018_04_09_17_20_34')
    op.drop_table('Move_2018_03_08_16_43_03')
    op.drop_table('Move_2018_04_01_14_07_54')
    op.drop_table('Move_2018_04_13_03_57_12')
    op.drop_table('Move_2018_03_11_17_07_23')
    op.drop_table('Move_2018_03_30_17_23_23')
    op.drop_table('Move_2018_03_17_17_16_48')
    op.drop_table('Move_2018_04_05_17_12_16')
    op.drop_table('Move_2018_03_27_17_11_13')
    op.drop_table('Move_2018_03_25_15_53_39')
    op.drop_table('Move_2018_04_08_14_21_08')
    op.drop_table('Move_2018_03_15_17_07_17')
    op.drop_table('Move_2018_03_28_17_11_16')
    op.drop_table('Move_2018_03_23_17_30_16')
    op.drop_table('Move_2018_04_10_17_30_44')
    op.drop_table('Move_2018_03_18_17_05_13')
    op.drop_table('Move_2018_03_13_17_29_57')
    op.drop_table('move_template')
    op.drop_table('Move_2018_03_10_16_35_00')
    op.drop_column('Moves', 'PaceZone2Time')
    op.drop_column('Moves', 'HRZone4Time')
    op.drop_column('Moves', 'PaceZone1Time')
    op.drop_column('Moves', 'HRZone1Time')
    op.drop_column('Moves', 'PaceZone4Time')
    op.drop_column('Moves', 'PaceZone5bTime')
    op.drop_column('Moves', 'AveragePace')
    op.drop_column('Moves', 'AverageCadence')
    op.drop_column('Moves', 'PaceZone5cTime')
    op.drop_column('Moves', 'HRZone5aTime')
    op.drop_column('Moves', 'HRZone3Time')
    op.drop_column('Moves', 'PaceZone3Time')
    op.drop_column('Moves', 'HRZone5cTime')
    op.drop_column('Moves', 'HRZone2Time')
    op.drop_column('Moves', 'PaceZone5aTime')
    op.drop_column('Moves', 'Calories')
    op.drop_column('Moves', 'HRZone5bTime')
    op.add_column('Plan', sa.Column('ID', sa.Integer(), nullable=False))
    op.add_column('Plan', sa.Column('TSScompl', sa.Integer(), nullable=True))
    op.drop_column('Plan', 'id')
    op.create_index(op.f('ix_UserDetails_Name'), 'UserDetails', ['Name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_UserDetails_Name'), table_name='UserDetails')
    op.add_column('Plan', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.drop_column('Plan', 'TSScompl')
    op.drop_column('Plan', 'ID')
    op.add_column('Moves', sa.Column('HRZone5bTime', mysql.TIME(), nullable=True))
    op.add_column('Moves', sa.Column('Calories', mysql.DECIMAL(precision=6, scale=2), nullable=True))
    op.add_column('Moves', sa.Column('PaceZone5aTime', mysql.TIME(), nullable=True))
    op.add_column('Moves', sa.Column('HRZone2Time', mysql.TIME(), nullable=True))
    op.add_column('Moves', sa.Column('HRZone5cTime', mysql.TIME(), nullable=True))
    op.add_column('Moves', sa.Column('PaceZone3Time', mysql.TIME(), nullable=True))
    op.add_column('Moves', sa.Column('HRZone3Time', mysql.TIME(), nullable=True))
    op.add_column('Moves', sa.Column('HRZone5aTime', mysql.TIME(), nullable=True))
    op.add_column('Moves', sa.Column('PaceZone5cTime', mysql.TIME(), nullable=True))
    op.add_column('Moves', sa.Column('AverageCadence', mysql.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('Moves', sa.Column('AveragePace', mysql.TIME(), nullable=True))
    op.add_column('Moves', sa.Column('PaceZone5bTime', mysql.TIME(), nullable=True))
    op.add_column('Moves', sa.Column('PaceZone4Time', mysql.TIME(), nullable=True))
    op.add_column('Moves', sa.Column('HRZone1Time', mysql.TIME(), nullable=True))
    op.add_column('Moves', sa.Column('PaceZone1Time', mysql.TIME(), nullable=True))
    op.add_column('Moves', sa.Column('HRZone4Time', mysql.TIME(), nullable=True))
    op.add_column('Moves', sa.Column('PaceZone2Time', mysql.TIME(), nullable=True))
    op.create_table('Move_2018_03_10_16_35_00',
    sa.Column('Id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('Activity', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('LapNum', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('LapStartTime', mysql.DATETIME(), nullable=True),
    sa.Column('LapDuration', mysql.TIME(), nullable=True),
    sa.Column('DistanceMeters', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('MaximumSpeed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Calories', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Timedelta', mysql.TIME(), nullable=True),
    sa.Column('Time', mysql.DATETIME(), nullable=True),
    sa.Column('Latitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Longitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Altitude', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Cadence', mysql.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('Speed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Pace', mysql.TIME(), nullable=True),
    sa.Column('HeartRate', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('HRZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('PaceZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('HrateIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('PaceIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('hrTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    sa.Column('pTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('move_template',
    sa.Column('Id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('Activity', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('LapNum', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('LapStartTime', mysql.DATETIME(), nullable=True),
    sa.Column('LapDuration', mysql.TIME(), nullable=True),
    sa.Column('DistanceMeters', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('MaximumSpeed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Calories', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Timedelta', mysql.TIME(), nullable=True),
    sa.Column('Time', mysql.DATETIME(), nullable=True),
    sa.Column('Latitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Longitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Altitude', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Cadence', mysql.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('Speed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Pace', mysql.TIME(), nullable=True),
    sa.Column('HeartRate', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('HRZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('PaceZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('HrateIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('PaceIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('hrTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    sa.Column('pTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('Move_2018_03_13_17_29_57',
    sa.Column('Id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('Activity', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('LapNum', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('LapStartTime', mysql.DATETIME(), nullable=True),
    sa.Column('LapDuration', mysql.TIME(), nullable=True),
    sa.Column('DistanceMeters', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('MaximumSpeed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Calories', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Timedelta', mysql.TIME(), nullable=True),
    sa.Column('Time', mysql.DATETIME(), nullable=True),
    sa.Column('Latitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Longitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Altitude', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Cadence', mysql.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('Speed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Pace', mysql.TIME(), nullable=True),
    sa.Column('HeartRate', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('HRZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('PaceZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('HrateIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('PaceIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('hrTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    sa.Column('pTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('Move_2018_03_18_17_05_13',
    sa.Column('Id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('Activity', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('LapNum', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('LapStartTime', mysql.DATETIME(), nullable=True),
    sa.Column('LapDuration', mysql.TIME(), nullable=True),
    sa.Column('DistanceMeters', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('MaximumSpeed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Calories', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Timedelta', mysql.TIME(), nullable=True),
    sa.Column('Time', mysql.DATETIME(), nullable=True),
    sa.Column('Latitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Longitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Altitude', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Cadence', mysql.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('Speed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Pace', mysql.TIME(), nullable=True),
    sa.Column('HeartRate', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('HRZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('PaceZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('HrateIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('PaceIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('hrTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    sa.Column('pTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('Move_2018_04_10_17_30_44',
    sa.Column('Id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('Activity', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('LapNum', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('LapStartTime', mysql.DATETIME(), nullable=True),
    sa.Column('LapDuration', mysql.TIME(), nullable=True),
    sa.Column('DistanceMeters', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('MaximumSpeed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Calories', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Timedelta', mysql.TIME(), nullable=True),
    sa.Column('Time', mysql.DATETIME(), nullable=True),
    sa.Column('Latitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Longitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Altitude', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Cadence', mysql.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('Speed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Pace', mysql.TIME(), nullable=True),
    sa.Column('HeartRate', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('HRZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('PaceZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('HrateIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('PaceIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('hrTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    sa.Column('pTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('Move_2018_03_23_17_30_16',
    sa.Column('Id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('Activity', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('LapNum', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('LapStartTime', mysql.DATETIME(), nullable=True),
    sa.Column('LapDuration', mysql.TIME(), nullable=True),
    sa.Column('DistanceMeters', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('MaximumSpeed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Calories', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Timedelta', mysql.TIME(), nullable=True),
    sa.Column('Time', mysql.DATETIME(), nullable=True),
    sa.Column('Latitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Longitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Altitude', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Cadence', mysql.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('Speed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Pace', mysql.TIME(), nullable=True),
    sa.Column('HeartRate', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('HRZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('PaceZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('HrateIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('PaceIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('hrTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    sa.Column('pTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('Move_2018_03_28_17_11_16',
    sa.Column('Id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('Activity', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('LapNum', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('LapStartTime', mysql.DATETIME(), nullable=True),
    sa.Column('LapDuration', mysql.TIME(), nullable=True),
    sa.Column('DistanceMeters', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('MaximumSpeed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Calories', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Timedelta', mysql.TIME(), nullable=True),
    sa.Column('Time', mysql.DATETIME(), nullable=True),
    sa.Column('Latitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Longitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Altitude', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Cadence', mysql.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('Speed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Pace', mysql.TIME(), nullable=True),
    sa.Column('HeartRate', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('HRZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('PaceZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('HrateIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('PaceIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('hrTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    sa.Column('pTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('Move_2018_03_15_17_07_17',
    sa.Column('Id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('Activity', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('LapNum', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('LapStartTime', mysql.DATETIME(), nullable=True),
    sa.Column('LapDuration', mysql.TIME(), nullable=True),
    sa.Column('DistanceMeters', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('MaximumSpeed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Calories', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Timedelta', mysql.TIME(), nullable=True),
    sa.Column('Time', mysql.DATETIME(), nullable=True),
    sa.Column('Latitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Longitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Altitude', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Cadence', mysql.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('Speed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Pace', mysql.TIME(), nullable=True),
    sa.Column('HeartRate', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('HRZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('PaceZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('HrateIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('PaceIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('hrTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    sa.Column('pTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('Move_2018_04_08_14_21_08',
    sa.Column('Id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('Activity', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('LapNum', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('LapStartTime', mysql.DATETIME(), nullable=True),
    sa.Column('LapDuration', mysql.TIME(), nullable=True),
    sa.Column('DistanceMeters', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('MaximumSpeed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Calories', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Timedelta', mysql.TIME(), nullable=True),
    sa.Column('Time', mysql.DATETIME(), nullable=True),
    sa.Column('Latitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Longitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Altitude', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Cadence', mysql.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('Speed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Pace', mysql.TIME(), nullable=True),
    sa.Column('HeartRate', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('HRZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('PaceZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('HrateIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('PaceIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('hrTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    sa.Column('pTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('Move_2018_03_25_15_53_39',
    sa.Column('Id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('Activity', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('LapNum', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('LapStartTime', mysql.DATETIME(), nullable=True),
    sa.Column('LapDuration', mysql.TIME(), nullable=True),
    sa.Column('DistanceMeters', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('MaximumSpeed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Calories', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Timedelta', mysql.TIME(), nullable=True),
    sa.Column('Time', mysql.DATETIME(), nullable=True),
    sa.Column('Latitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Longitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Altitude', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Cadence', mysql.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('Speed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Pace', mysql.TIME(), nullable=True),
    sa.Column('HeartRate', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('HRZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('PaceZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('HrateIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('PaceIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('hrTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    sa.Column('pTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('Move_2018_03_27_17_11_13',
    sa.Column('Id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('Activity', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('LapNum', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('LapStartTime', mysql.DATETIME(), nullable=True),
    sa.Column('LapDuration', mysql.TIME(), nullable=True),
    sa.Column('DistanceMeters', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('MaximumSpeed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Calories', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Timedelta', mysql.TIME(), nullable=True),
    sa.Column('Time', mysql.DATETIME(), nullable=True),
    sa.Column('Latitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Longitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Altitude', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Cadence', mysql.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('Speed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Pace', mysql.TIME(), nullable=True),
    sa.Column('HeartRate', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('HRZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('PaceZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('HrateIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('PaceIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('hrTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    sa.Column('pTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('Move_2018_04_05_17_12_16',
    sa.Column('Id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('Activity', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('LapNum', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('LapStartTime', mysql.DATETIME(), nullable=True),
    sa.Column('LapDuration', mysql.TIME(), nullable=True),
    sa.Column('DistanceMeters', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('MaximumSpeed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Calories', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Timedelta', mysql.TIME(), nullable=True),
    sa.Column('Time', mysql.DATETIME(), nullable=True),
    sa.Column('Latitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Longitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Altitude', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Cadence', mysql.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('Speed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Pace', mysql.TIME(), nullable=True),
    sa.Column('HeartRate', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('HRZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('PaceZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('HrateIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('PaceIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('hrTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    sa.Column('pTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('Move_2018_03_17_17_16_48',
    sa.Column('Id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('Activity', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('LapNum', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('LapStartTime', mysql.DATETIME(), nullable=True),
    sa.Column('LapDuration', mysql.TIME(), nullable=True),
    sa.Column('DistanceMeters', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('MaximumSpeed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Calories', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Timedelta', mysql.TIME(), nullable=True),
    sa.Column('Time', mysql.DATETIME(), nullable=True),
    sa.Column('Latitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Longitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Altitude', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Cadence', mysql.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('Speed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Pace', mysql.TIME(), nullable=True),
    sa.Column('HeartRate', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('HRZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('PaceZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('HrateIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('PaceIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('hrTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    sa.Column('pTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('Move_2018_03_30_17_23_23',
    sa.Column('Id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('Activity', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('LapNum', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('LapStartTime', mysql.DATETIME(), nullable=True),
    sa.Column('LapDuration', mysql.TIME(), nullable=True),
    sa.Column('DistanceMeters', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('MaximumSpeed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Calories', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Timedelta', mysql.TIME(), nullable=True),
    sa.Column('Time', mysql.DATETIME(), nullable=True),
    sa.Column('Latitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Longitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Altitude', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Cadence', mysql.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('Speed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Pace', mysql.TIME(), nullable=True),
    sa.Column('HeartRate', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('HRZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('PaceZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('HrateIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('PaceIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('hrTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    sa.Column('pTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('Move_2018_03_11_17_07_23',
    sa.Column('Id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('Activity', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('LapNum', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('LapStartTime', mysql.DATETIME(), nullable=True),
    sa.Column('LapDuration', mysql.TIME(), nullable=True),
    sa.Column('DistanceMeters', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('MaximumSpeed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Calories', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Timedelta', mysql.TIME(), nullable=True),
    sa.Column('Time', mysql.DATETIME(), nullable=True),
    sa.Column('Latitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Longitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Altitude', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Cadence', mysql.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('Speed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Pace', mysql.TIME(), nullable=True),
    sa.Column('HeartRate', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('HRZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('PaceZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('HrateIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('PaceIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('hrTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    sa.Column('pTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('Move_2018_04_13_03_57_12',
    sa.Column('Id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('Activity', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('LapNum', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('LapStartTime', mysql.DATETIME(), nullable=True),
    sa.Column('LapDuration', mysql.TIME(), nullable=True),
    sa.Column('DistanceMeters', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('MaximumSpeed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Calories', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Timedelta', mysql.TIME(), nullable=True),
    sa.Column('Time', mysql.DATETIME(), nullable=True),
    sa.Column('Latitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Longitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Altitude', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Cadence', mysql.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('Speed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Pace', mysql.TIME(), nullable=True),
    sa.Column('HeartRate', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('HRZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('PaceZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('HrateIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('PaceIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('hrTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    sa.Column('pTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('Move_2018_04_01_14_07_54',
    sa.Column('Id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('Activity', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('LapNum', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('LapStartTime', mysql.DATETIME(), nullable=True),
    sa.Column('LapDuration', mysql.TIME(), nullable=True),
    sa.Column('DistanceMeters', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('MaximumSpeed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Calories', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Timedelta', mysql.TIME(), nullable=True),
    sa.Column('Time', mysql.DATETIME(), nullable=True),
    sa.Column('Latitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Longitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Altitude', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Cadence', mysql.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('Speed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Pace', mysql.TIME(), nullable=True),
    sa.Column('HeartRate', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('HRZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('PaceZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('HrateIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('PaceIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('hrTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    sa.Column('pTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('Move_2018_03_08_16_43_03',
    sa.Column('Id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('Activity', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('LapNum', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('LapStartTime', mysql.DATETIME(), nullable=True),
    sa.Column('LapDuration', mysql.TIME(), nullable=True),
    sa.Column('DistanceMeters', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('MaximumSpeed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Calories', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Timedelta', mysql.TIME(), nullable=True),
    sa.Column('Time', mysql.DATETIME(), nullable=True),
    sa.Column('Latitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Longitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Altitude', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Cadence', mysql.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('Speed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Pace', mysql.TIME(), nullable=True),
    sa.Column('HeartRate', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('HRZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('PaceZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('HrateIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('PaceIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('hrTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    sa.Column('pTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('Move_2018_04_09_17_20_34',
    sa.Column('Id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('Activity', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('LapNum', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('LapStartTime', mysql.DATETIME(), nullable=True),
    sa.Column('LapDuration', mysql.TIME(), nullable=True),
    sa.Column('DistanceMeters', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('MaximumSpeed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Calories', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Timedelta', mysql.TIME(), nullable=True),
    sa.Column('Time', mysql.DATETIME(), nullable=True),
    sa.Column('Latitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Longitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Altitude', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Cadence', mysql.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('Speed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Pace', mysql.TIME(), nullable=True),
    sa.Column('HeartRate', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('HRZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('PaceZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('HrateIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('PaceIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('hrTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    sa.Column('pTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('Move_2018_04_03_17_13_06',
    sa.Column('Id', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('Activity', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('LapNum', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('LapStartTime', mysql.DATETIME(), nullable=True),
    sa.Column('LapDuration', mysql.TIME(), nullable=True),
    sa.Column('DistanceMeters', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('MaximumSpeed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Calories', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Timedelta', mysql.TIME(), nullable=True),
    sa.Column('Time', mysql.DATETIME(), nullable=True),
    sa.Column('Latitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Longitude', mysql.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('Altitude', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Cadence', mysql.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('Speed', mysql.DECIMAL(precision=9, scale=3), nullable=True),
    sa.Column('Pace', mysql.TIME(), nullable=True),
    sa.Column('HeartRate', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('HRZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('PaceZone', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('HrateIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('PaceIF', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('hrTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    sa.Column('pTSS', mysql.DECIMAL(precision=5, scale=3), nullable=True),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
