"""empty message

Revision ID: c5aaf7bd32ee
Revises: db882b458f69
Create Date: 2019-02-10 21:59:12.679198

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c5aaf7bd32ee'
down_revision = 'db882b458f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('Plan', sa.Column('date', sa.Date(), nullable=True))
    # op.add_column('Plan', sa.Column('training_phase', sa.String(length=128), nullable=True))
    # op.add_column('Plan', sa.Column('tss_compl', sa.Integer(), nullable=True))
    # op.add_column('Plan', sa.Column('tss_plan', sa.Integer(), nullable=True))
    # op.add_column('Plan', sa.Column('week', sa.Integer(), nullable=True))
    # op.drop_column('Plan', 'Week')
    # op.drop_column('Plan', 'TSSplan')
    # op.drop_column('Plan', 'Date')
    # op.drop_column('Plan', 'TrainingPhase')
    # op.drop_column('Plan', 'TSScompl')
    # op.add_column('testPlan', sa.Column('date', sa.Date(), nullable=True))
    # op.add_column('testPlan', sa.Column('training_phase', sa.String(length=128), nullable=True))
    # op.add_column('testPlan', sa.Column('tss_compl', sa.Integer(), nullable=True))
    # op.add_column('testPlan', sa.Column('tss_plan', sa.Integer(), nullable=True))
    # op.drop_column('testPlan', 'TSScompl')
    # op.drop_column('testPlan', 'TSSplan')
    # op.drop_column('testPlan', 'Date')
    # op.drop_column('testPlan', 'TrainingPhase')

    op.alter_column('testPlan', 'TrainingPhase', new_column_name='training_phase', existing_type=sa.String(length=128), existing_server_default=False, existing_nullable=None)
    # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('testPlan', sa.Column('TrainingPhase', mysql.VARCHAR(length=128), nullable=True))
#     op.add_column('testPlan', sa.Column('Date', sa.DATE(), nullable=True))
#     op.add_column('testPlan', sa.Column('TSSplan', mysql.DECIMAL(precision=10, scale=0), nullable=True))
#     op.add_column('testPlan', sa.Column('TSScompl', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
#     op.drop_column('testPlan', 'tss_plan')
#     op.drop_column('testPlan', 'tss_compl')
#     op.drop_column('testPlan', 'training_phase')
#     op.drop_column('testPlan', 'date')
#     op.add_column('Plan', sa.Column('TSScompl', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
#     op.add_column('Plan', sa.Column('TrainingPhase', mysql.VARCHAR(length=128), nullable=True))
#     op.add_column('Plan', sa.Column('Date', sa.DATE(), nullable=True))
#     op.add_column('Plan', sa.Column('TSSplan', mysql.DECIMAL(precision=10, scale=0), nullable=True))
#     op.add_column('Plan', sa.Column('Week', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
#     op.drop_column('Plan', 'week')
#     op.drop_column('Plan', 'tss_plan')
#     op.drop_column('Plan', 'tss_compl')
#     op.drop_column('Plan', 'training_phase')
#     op.drop_column('Plan', 'date')
#     # ### end Alembic commands ###
