"""empty message

Revision ID: db882b458f69
Revises: 28308995a746
Create Date: 2019-02-10 21:44:22.540615

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db882b458f69'
down_revision = '28308995a746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('testPlan', sa.Column('date', sa.Date(), nullable=True))
    # op.add_column('testPlan', sa.Column('training_phase', sa.String(length=128), nullable=True))
    # op.add_column('testPlan', sa.Column('tss_compl', sa.Integer(), nullable=True))
    # op.add_column('testPlan', sa.Column('tss_plan', sa.Integer(), nullable=True))
    # op.add_column('testPlan', sa.Column('week', sa.Integer(), nullable=True))
    # op.drop_column('testPlan', 'Week')
    # op.drop_column('testPlan', 'TSSplan')
    # op.drop_column('testPlan', 'TrainingPhase')
    # op.drop_column('testPlan', 'Date')
    # op.drop_column('testPlan', 'TSScompl')
    op.alter_column('testPlan', 'Week', new_column_name='week', existing_type=sa.Integer(), existing_server_default=False, existing_nullable=None)
    # ### end Alembic commands ###


#def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('testPlan', sa.Column('TSScompl', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # op.add_column('testPlan', sa.Column('Date', sa.DATE(), nullable=True))
    # op.add_column('testPlan', sa.Column('TrainingPhase', mysql.VARCHAR(length=128), nullable=True))
    # op.add_column('testPlan', sa.Column('TSSplan', mysql.DECIMAL(precision=10, scale=0), nullable=True))
    # op.add_column('testPlan', sa.Column('Week', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    # op.drop_column('testPlan', 'week')
    # op.drop_column('testPlan', 'tss_plan')
    # op.drop_column('testPlan', 'tss_compl')
    # op.drop_column('testPlan', 'training_phase')
    # op.drop_column('testPlan', 'date')

    # ### end Alembic commands ###
